s="TTACGACTGGTGAAGAAGCTCAGGCTGGTAAGTGAGGGAGCCTTGGGGTGTAGCGGTATGCTTTACGACGTCCTGTGTTGGGCCAAACTGACCTGAAGCACAAGATTCTAGAATTTTACAACGGCCAATCTTCACTTTAGCGTAAGCTCGTTAGTTTTTAAAGATTACCGACCGGCAATACGGTGCATTATGCGGTTTGCCTAATTTAGTACCAATATACCACGAGAGAGGCCAGAGGTATAGTCCCTAGTCAGTACCCGACTAGTCCTGTATGGTATGACCTATTCGCGTCACGGAGGGACAGCGCCCCTCGACCCTCAGCCTCACTCCGCTTCGAGCAGCAACTTGTACTGGCTCTCACTATCTGCCCACTTAAGTGTAAACCGCGGTAAACTTCGCATCTATTGTGAATAGATTGATGCGTCGCCGGTACTGCTTTAGTCAATGTCCTAACTGCAGAGCGAACGAAGATTATCATTCACAATGGGGAGCGCTCCAAACGTATCGATACAGTTTCTCTAACCTTCATGAGCCATGATTGATGCCGCATAGATGGTAATGTCACCCAAGCACGGGTTCAATAATCGGTCTTTATGGCCGGAATTACCTCGTCCTATTGCGAACGGTGGACCAGGGTCTCTCACTTTCCAACATTCCTTCAGGAGCAATATTGAACATTAGAACCAGGAATAGTAGCCGTGCACGTCTAGCCAACGGAGAGACTCAAGGCTGAGTCTTCTTTGCCTAGGCAAGAGTTATACCCAGCGATCCTCGGCCAACAGTAAGTTGTCGCTGGTAAATCAGCTAGATAAAAAGGATCGTATTCTGTACCCAACCCGCTAGCGGAGCGTTCCGGTCATCCTA"

count_a=0
count_t=0
count_g=0
count_c=0

for base in s:
    if base=="A":
        count_a +=1
    elif base=="T":
        count_t +=1
    elif base =="G":
        count_g +=1
    else:
        count_c +=1

print(count_a,count_c,count_g,count_t)
